### ISSUE TITLE
Degrading Profiles with Dice in there Attacks

### ISSUE THREAD

**Issue by Otwald** [Floppy/dataslate#1065]
so i loaded in a model that changes its attack numbers when degrading,
for all the attacks you have to dice it shows up like this 
Chaos Land Raider is a good example for that

![grafik](https://user-images.githubusercontent.com/19661864/212529555-b88639f2-2ba5-444b-8e4d-fc6eaa401f2a.png)

**Comment by Floppy** [comment]
Nice one, thanks! I'll fix it.

**Comment by Floppy** [comment]
Should be fixed!
