### ISSUE TITLE
Missing Heavy Gunner operative

### ISSUE THREAD

**Issue by rlancemoody** [Floppy/dataslate#508]
This almost works with the new Kill Team.  Would be wonderful if you could fix it to do so.

Right now, leaves off some operatives from document.

Also would be great to get damage and critical damage together.

See enclosed
[Death Guard Kill Team.zip](https://github.com/Floppy/dataslate/files/7131657/Death.Guard.Kill.Team.zip)

**Comment by Floppy** [comment]
@rlancemoody Glad to hear it's at least semi-working! I did a bunch of work to get it that far before the game released, but then haven't had time to finish it since for various reasons. Thanks for the example file, interesting that it's leaving off some operatives. I'll get back into the code and see if I can get it finished off in the next few days. I want to use it myself too :)

**Comment by rlancemoody** [comment]
Great!   Thanks!

**Comment by Floppy** [comment]
OK, I see that the Heavy Gunner is missing. I'll work it out :)

**Comment by Floppy** [comment]
Looking into this I think this is an error in the Battlescribe data, the operative is showing as `type="upgrade"` rather than `type="model"` in the roster file. I'll check the source data.

**Comment by Floppy** [comment]
Might also be able to be more generous with how we search for the operatives in the XML.

**Comment by Floppy** [comment]
I've submitted a fix to the Battlescribe data in https://github.com/BSData/wh40k-killteam/pull/669

**Comment by Floppy** [comment]
Should be fixed in the next release! 👍🏻 

I'm going to close this as fixed regarding the missing operative; rest assured that full KT21 support is incoming :)

**Comment by rlancemoody** [comment]
You are awesome.   I know you probably get dumb requests a lot but it would be wonderful if you could generate a card with the faction special rules on it that would appear at the end of the team list.   Then we would have everything on one great looking page (or two).

**Comment by Floppy** [comment]
I'd like to do that but the data isn't in Battlescribe at all, so I'd have to either write it up myself, risking copyright strike, or pull it in somehow from somewhere else. I'll have a think, as I agree it would be bloody useful.

**Comment by rlancemoody** [comment]
Hi James, I was referring to this data (as an example from Battlescribe).  This must be in the data set, no?

![Screenshot 2021-09-12 134811](https://user-images.githubusercontent.com/90353472/132997623-3b544ec1-29b5-445b-9784-ab5a28a0ce5e.png)

**Comment by Floppy** [comment]
Ah, sorry, gotcha. I suspect that's covered by #513 , which I'm working on at the moment :)
