### ISSUE TITLE
KT21 - T'au roster doesn't load

### ISSUE THREAD

**Issue by fivaldrood** [Floppy/dataslate#517]
I can get other rosters to load, but nothing with T'au is working.

[Final Tau.zip](https://github.com/Floppy/dataslate/files/7150093/Final.Tau.zip)

**Comment by Floppy** [comment]
Thanks! I'll investigate.

**Comment by Floppy** [comment]
Error when loading in dev:

```
Unhandled Rejection (TypeError): can't access property "toString", xpSelect(...) is undefined
```

at src/parsers/KillTeam2021/BattlescribeParser.ts:25

**Comment by Floppy** [comment]
Looks like something is missing a critical rule in the data, and I'm not handling the error well. Will need to fix in both places I suspect.

**Comment by Floppy** [comment]
OK, yeah, the critical rule on the Burst Cannon is empty (rather than `-` as it normally is), and my code assumes there's always _something_ there. I'll update it to be more tolerant.

**Comment by Floppy** [comment]
Fixed now 👍🏻 

You might need to do a cache clear to get the latest version, but it should work now.

**Comment by fivaldrood** [comment]
Not sure if this is how its supposed to work but I am seeing 5 instances of Stealth Battlesuit Shas'ui when I load the same roster.  Isn't it supposed to collapse those all down to 1?

(Not sure if there is a better place to message you things like this like a discord?)
Thanks for your work on this!

**Comment by Floppy** [comment]
No, this is the best place, keep track of the bugs :)

It's not currently collapsing identical models in this version, though I'll bring it back soon.

**Comment by Floppy** [comment]
Added https://github.com/Floppy/dataslate/issues/518 to remind me.

**Comment by Floppy** [comment]
That should be done now :)
