### ISSUE TITLE
Show a wound tracker for every model

### ISSUE THREAD

**Issue by Floppy** [Floppy/dataslate#523]
Reported via [reddit](https://www.reddit.com/r/killteam/comments/po1gk8/i_made_a_website_that_converts_kill_team_rosters/hcwi2xx/?utm_source=reddit&utm_medium=web2x&context=3):

> I have a TS kill team version with two warriors. Your tool just marks the Warrior data card with "2 x Rubric Marine (Warrior)".
> This is OK but any chance for distinct wound tracks that could be placed to the right of the card matching the count of duplicates? In this case to the right of the warrior card would be two wound tracks, one for each warrior.

**Comment by fivaldrood** [comment]
Is it possible to make this an option?  We tend to track wounds with dice on the specific models.

**Comment by Floppy** [comment]
Yeah, probably. Or only include it on printouts or something. I'm trying to make it more compact at the moment too.
