### ISSUE TITLE
Missing abilities and kit?

### ISSUE THREAD

**Issue by Floppy** [Floppy/dataslate#525]
This might be down to things not being implemented yet, but as reported on [reddit](https://www.reddit.com/r/killteam/comments/po1gk8/i_made_a_website_that_converts_kill_team_rosters/hcvbpw7/?utm_source=reddit&utm_medium=web2x&context=3):

> Interesting ... it doesn't seem to add all abilities to the cards though. For example I have an immortal leader with Starfire core, and the Weave ... it lists the core, but not the weave on the abilities.
> Similarily with my warriors, it shows 5x warriors, but one of them had mind shackle scarabs, and they are not showing on the card anywhere.

[New Roster.rosz.zip](https://github.com/Floppy/dataslate/files/7168951/New.Roster.rosz.zip)

**Comment by Floppy** [comment]
Mindshackle Scarabs are now showing...

**Comment by rlancemoody** [comment]
Wow things are really starting to look great! Thanks for all the work!  Hope you can keep iterating.

**Comment by Floppy** [comment]
This is all fixed now!
