### ISSUE TITLE
Identical operatives with names could still be shown as a single datasheet with multiple named wound tracks

### ISSUE THREAD

**Issue by r4dian** [Floppy/dataslate#528]
At the moment if you have a bunch of basic troops, they get 1 datasheet entry, and multiple wound tracks appear to the side.

If you name those operatives in Battlescribe, then a datasheet is shown for each.

It would save a bit of space when printing, if the names just appeared on the wound tracks.

**Comment by Floppy** [comment]
That's exactly what I was thinking of doing, when I realised that multiple wound tracks would need labelling! Great minds think alike ;)

**Comment by Floppy** [comment]
Actually I hadn't thought about removing the repeated sheets for operatives with different names. **Only** displaying the name as a title on the wound track makes a lot of sense.

**Comment by Floppy** [comment]
This is in progress. It's not quite right yet but I'm getting there.

**Comment by Floppy** [comment]
Done!
