### ISSUE TITLE
Should display the operatives in the same order as in Battlescribe

### ISSUE THREAD

**Issue by r4dian** [Floppy/dataslate#529]
Battlescribe groups similar operatives together on the roster.

This displays them in the order they were added instead.

Example:

Create a roster with a Thousand Sons force
Add 2 Rubrics
Add 6 Tzangoors
Add 2 more rubrics

Battlescribe displays all the Rubric marines, then all the Tzaangors,
This tool displays them 2/6/2 as they were added.

**Comment by r4dian** [comment]
In addition, the leader(s) go as the top entry in Battlescribe.

**Comment by Floppy** [comment]
Thanks! I'll see if I can work out the ordering they use. Obviously it doesn't pass through to the roster file, which must go in order of addition.

**Comment by Floppy** [comment]
OK, I've verified this myself. The thing to do is order the models alphabetically, I think, and bump the Leader up to the top.
