### ISSUE TITLE
HighlightedText drops any instances of replaced symbol after the first

### ISSUE THREAD

**Issue by lstrzebinczyk** [Floppy/dataslate#561]
Check the screenshot from my ongoing PR:
![Dataslate](https://user-images.githubusercontent.com/1272828/135149662-3f4d0fdf-63fc-4b39-975b-6f616eab7a68.png)

In the place where arrow leads, the data contains another ⬟, but it gets dropped instead of replaced with colored version.

EDIT

This could be a nice opportunity to introduce some unit tests: )

EDIT2

If there are multiple symbols to be replaced, but of different types, any after the first one are simply ignored

**Comment by Floppy** [comment]
Oops. Yeah, this definitely needs tests. There are some, but they're wildly insufficient :)

**Comment by lstrzebinczyk** [comment]
I'll close the ticket, since it is done now: )

**Comment by Floppy** [comment]
perfect :)
