### ISSUE TITLE
Include faction archetype in the roster

### ISSUE THREAD

**Issue by lstrzebinczyk** [Floppy/dataslate#566]
Hey!

I just learned today, that factions have archetypes, which restrict which tac-ops can be taken by that faction. IMO that should be included in the roster: ). This information doesn't seem to be available in the battlescribe data. What do you think?

**Comment by Floppy** [comment]
Yep, makes sense to add that to the faction-specific data! Good call!

**Comment by lstrzebinczyk** [comment]
I started looking into that one, and while with kriegs and commandos the situation is simple, it's not that simple for the compendium teams. Compendium kill teams are built from fire teams, each of which can have their own archetypes. So which archetypes a given roster has access too ultimately depends on the way roster is built.

It seems like this information should be included per fireteam, from Battlescribes output. @Floppy WDYT?

**Comment by Floppy** [comment]
Hm, yeah, we can detect fire teams and do the lookup, I think they go in as `force`s. Will have to have a look.

**Comment by g3rg** [comment]
I just had a look at the XML, and yes, the fireteams are 'force' elements. 

I'd be happy to pick this up to work on if no one else has yet?

**Comment by lstrzebinczyk** [comment]
Go for it : )

**Comment by Floppy** [comment]
Done by @g3rg in #581
