### ISSUE TITLE
Use markdown for ploy and tac ops descriptions

### ISSUE THREAD

**Issue by lstrzebinczyk** [Floppy/dataslate#573]
There is a lot of variability in the tac ops and the ploys. Ploys right now have 4 edge cases. Additionally, the text is bold in some cases, and that is not represented in our text.

I suggest a solution to that issue: let's keep description of ploys, tac ops, and whatever else applies as markdown text. 
This will allow us to encode the options, text post options, even table to represent weapon. Also it will allow us to bold some parts.
Action will probably have to stay as a separate field, and always be at the end.

@Floppy @g3rg what do you guys think?

**Comment by Floppy** [comment]
Yes, I was thinking along the very same lines, to use markdown instead of the structure we currently have. You just know that GW will release something that breaks our format as soon as we settle on it.

**Comment by g3rg** [comment]
As I was filling in the data, the lack of being able to 'bold' things did make me think of using Markdown, so I think it's a good idea as well.

**Comment by lstrzebinczyk** [comment]
I would love to look into using markdown over the week.

**Comment by Floppy** [comment]
I wonder if there's a markdown system where you can add your own syntax processing...
