### ISSUE TITLE
Some text in the ADEPTA SORORITAS Divine Guidance Strategic Ploy is duplicated.

### ISSUE THREAD

**Issue by AlanDNelson** [Floppy/dataslate#574]
Until the end of the Turning Point, each time a friendly ADEPTA SORORITAS operative fights in combat or makes a shooting attack, in the Roll Attack Dice step of that combat or shooting attack, **in the Roll Attack Dice step of that combat or shooting attack,** if you retain any critical hits, you can re-roll one of your attack dice.

**Comment by lstrzebinczyk** [comment]
Looks like this here contains the duplication: https://github.com/Floppy/dataslate/blob/main/src/components/KillTeam2021/data/ecclesiarchy.ts#L7-L8
