### ISSUE TITLE
standard.js does not lint typescript files

### ISSUE THREAD

**Issue by lstrzebinczyk** [Floppy/dataslate#576]
And as such, no files in this project are linted currently. Options include:
  - using https://github.com/standard/ts-standard
  - using regular eslint with https://github.com/standard/eslint-config-standard

**Comment by Floppy** [comment]
You know, I'd wondered why I hadn't run up against many lint errors during the KT21 dev.

headdesk.gif

**Comment by Floppy** [comment]
@lstrzebinczyk @g3rg as I've fixed the linter, there are a LOT of formatting and other small changes across the entire repo. If  you were working on any branches and this makes life difficult for you, I apologise 😄
