### ISSUE TITLE
Dataslate discord channel?

### ISSUE THREAD

**Issue by lstrzebinczyk** [Floppy/dataslate#617]
Should we get one? It would be nice to have a place to chat and discuss ideas. Also, maybe be accessible by the community?

**Comment by g3rg** [comment]
I'm happy to join a discord server to discuss things. I had been thinking of using the GitHub Wiki, but discord would make more sense.

Also, I'm in Australia (GMT+10) in case it helps with any coordination etc.

**Comment by g3rg** [comment]
Discord created, and link added.
