### ISSUE TITLE
KT 2021 - Rules such as Cult Ambush for Wyrmblade not display on model

### ISSUE THREAD

**Issue by g3rg** [Floppy/dataslate#768]
Currently rules such as 'Cult Ambush' for Wyrmblade, and 'Favoured of the Dark Gods' for Legionairy kill teams doesn't show on which models it applies to. There are probably other examples as well.

In the BattleScribe data it is a 'rule', not a category or ability.

**Comment by Floppy** [comment]
Probably needs a tweak to the parser; good spot.

**Comment by g3rg** [comment]
Once I've got the new teams added, hopefully today, I was going to take a look and see if this kind of thing is consistent between teams in BattleScribe, as I've noticed the "Aeldari Raiders" ability for the new Corsair team does show up. I want to make sure with Mad Spy that its intentional before fixing in the parser.

**Comment by Floppy** [comment]
Sounds good, thanks!

**Comment by g3rg** [comment]
Got a reply from Mad Spy, the data is as intended.

Parser is fine, it's picking up the rules and putting it on the operative/datacard object. So it's a change to the UI to display those rules. 

I've made a prototype that puts non-standard rules on a line below keywords, but I feel there could be a better way to display it. If you want to take a look @Floppy and give any feedback, just upload a Wyrmblade team and look at Cult Ambush on any operative, and if you include a Kelermorph it has Cult Ambush and Preternatural Assassin:

http://dataslate.s3-website-ap-southeast-2.amazonaws.com/

**Comment by Floppy** [comment]
Nice, I see it. I wonder if it would be more obvious if they were listed in a small "Rules" box like Equipment and Abilities?  I missed them initially, and I thought I knew what I was looking for :)

**Comment by g3rg** [comment]
Makes sense, I'll give that a go and publish it later today for review.

**Comment by g3rg** [comment]
Updated, started looking at a separate block. I've got it now showing as 'pills' within the abilities block and agree, it looks a lot better, but can still look at updating it to merge non-standard rules into abilities list and display the full text if you think that would be better? That would start making cards a lot bigger, vs just keeping the rule name and then finding them in the reference page?

http://dataslate.s3-website-ap-southeast-2.amazonaws.com/

**Comment by Floppy** [comment]
More obvious, definitely. Maybe make the title the same style as the abilities, and then add description text saying "See Rules section below" to avoid repeating lots of text each time? I guess many of these will apply to multiple models, right?
